//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApiTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string OrderName { get; set; }
        public string OrderAddress { get; set; }
        public string OrderFrom { get; set; }
        public string OrderTo { get; set; }
        public string DestinationFrom { get; set; }
        public string DestinationTo { get; set; }
        public string CurrentLocation { get; set; }
        public double Distance { get; set; }
        public string PaymentMode { get; set; }
        public string DrivingMode { get; set; }
        public double TotalAmount { get; set; }
        public bool Status { get; set; }
    }
}
